config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :posts do
    resources :comments, only: %i[new create]
  end

  resources :comments, only: [:destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.new(comment_params)
    @comment.post = @post
    @comment.user = current_user
    if @comment.save
      redirect_to post_path(@post), notice: "Comment posted 👌"
    else
      redirect_to post_path(@post), notice: "Comment can't blank"
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.delete
    redirect_to posts_path
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :post_id, :user_id)
  end

  def find_comment
    @comment = Comment.find(params[:comments_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find, only: %i[edit show update destroy]
  def index
    @posts = Post.all
    @user = current_user
  end

  def edit
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create(post_params)
    @post.user = current_user
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @user = current_user
  end

  def update
    @post.update(post_params)
    redirect_to posts_path
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :url, :user_id)
  end

  def find
    @post = Post.find(params[:id])
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSharePostsChallenge</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/2.0.2/anime.min.js"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class='title'>
  <div>
    <h1>Rails Share Posts Challenge</h1>
    <h2>2021-12-16</h2>
    <%= link_to 'Enter', posts_path, class: "btn btn-ghost" %>
  </div>

</div>

app/views/posts/edit.html.erb
<%= render 'shared/form', post: @post %>

app/views/posts/index.html.erb
<div class='cards'>
  <div>
  <% @posts.each do |post| %>
    <%= link_to post do %>
      <div class="card-product">
        <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
        <div class="card-product-infos">
          <h2><%= post.title %></h2>
          <p><%= post.url %></p>
          <div class='action'>
            <% if (user_signed_in? && @user.id == post.user_id) %>
              <%= link_to 'Update', edit_post_path(post), method: :get, class: "btn btn-ghost" %>
              <%= link_to 'Delete', post_path(post), method: :delete, class: "btn btn-ghost",
            data: { confirm: "Are you sure?" } %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<%= render 'shared/form', post: @post %>

app/views/posts/show.html.erb
<div class='post'>
  <h2><%= @post.title %></h2>
  <div class ='article'>
    <div class='attachment'>
    <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
      <div class ='text'>
        <p><%= @post.content %></p>
        <p><%=link_to @post.url, @post.url, :target => "_blank" %></p>
        <br>
      </div>
    </div>
    <div class='container'>
      <div class ='comment_container'>
        <% @post.comments.each do |comment| %>
        <div class ='comment'>
          <p><%= comment.content%></p>
          <% if (user_signed_in? && @user.id == comment.user_id) %>
            <%= link_to "Delete", comment_path(comment), method: :delete, data: { confirm: "Are you sure?" },class: "btn btn-ghost" %> <br>
          <% end%>
        </div>
        <% end %>
      </div>
    <%= render 'shared/new_comment' %>
    </div>
  </div>
  <%= link_to 'Back to the list', posts_path,class: "btn btn-ghost" %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/shared/_form.html.erb
<div class='item'>
  <div class="create">
    <div class="form">
      <%= simple_form_for(@post) do |f| %>
      <%= f.error_notification %>
      <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

      <div class="form-inputs">
        <%= f.label "Title"%>
        <%= f.input :title, label: false%>
        <%= f.label "Content" %>
        <%= f.input :content, as: :text,:input_html => {:rows => 10}, label: false%>
        <%= f.label "Url" %>
        <%= f.input :url, label: false%>
      </div>
        <br><br>

      <div class="form-actions">
        <%= f.button :submit, class: "btn btn-ghost"  %>
      </div>

      <% end %>
    </div>
  </div>
  <%= link_to 'Back to the list', posts_path,class: "btn btn-ghost" %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="navbar-brand">
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    Rails Share Posts Challenge
    </div>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", posts_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Create your post", new_post_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_new_comment.html.erb
<div class='addcomment'>
  <div>
    <h3>New Comment</h3>

    <%= simple_form_for([@post, @comment], url: post_comments_path(@post)) do |f| %>
      <%= f.input :content, as: :text, label: false  %>
      <%= f.button :submit, class: "btn btn-ghost"%>
    <% end %>
  </div>

</div>